### ISSUE TITLE
Extracting Album Art from MP3 File in AWS S3

### ISSUE THREAD

**Issue by shawlz** [aadsm/JavaScript-ID3-Reader#49]
Hello, 

I have files MP3 in S3 and I'll like to extract the tags and album art from the files. I'm currently extracting successfully the tags but the picture tag is not extracted. 

When I use the FileReader API when the MP3 file is on local storage it extracts it successfully. Can you please advise on how I can achieve this on S3?

**Comment by aadsm** [comment]
What do you mean with the mp3 files being on local storage?
I don't think there should be any difference between having the file on S3 or any other http server.

**Comment by zyonnetworks** [comment]
Same issue here. I cannot extract artwork when trying to read from S3

ID3.loadTags(http://s3.aws.com/file.mp3, function () {...

**Comment by ayazhussein** [comment]
do I have to download the mp3 files to extract the artwork or just extract it from s3 file directly?

**Comment by aadsm** [comment]
I'm not sure if I understand your question. The library will download the
necessary bytes to read the artwork.

Also, please use jsmediatags as I no longer support this one.
