### ISSUE TITLE
not working in cordova / phonega

### ISSUE THREAD

**Issue by cinder92** [aadsm/JavaScript-ID3-Reader#50]
hello, in web browser, this plugin works perfectly, but when i compile the apk and then install on my phone, plugin only return object in console.log(ID3) => {}.

thanks!

**Comment by aadsm** [comment]
I haven't done cordova development so I'm not sure the proper way to read files, but pretty sure the problem is that an http request doesn't work to read local files.
There was someone with similar problem last year, maybe it can help you? https://github.com/aadsm/JavaScript-ID3-Reader/issues/39

**Comment by aadsm** [comment]
@cfjedimaster wrote a pretty cool blog post about using this library in Cordova: http://www.raymondcamden.com/2015/04/30/working-with-mp3s-id3-and-phonegapcordova-2

**Comment by cinder92** [comment]
thanks a lot, i'll check it!
