### ISSUE TITLE
loadFromLink() doesn't work

### ISSUE THREAD

**Issue by RutSzymon** [aadsm/JavaScript-ID3-Reader#55]
I followed the documentation and example: http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/

This is my code:
```coffeescript
class Mfolio.Views.SongsEdit extends Marionette.ItemView
  template: JST["songs/edit"]

  events:
    "change #song_image": "loadFromFile"

  onRender: ->
    @loadFromLink()

  loadFromFile: ->
    file = $("#song_image")[0].files[0]
    url = file.urn or file.name
    @loadUrl url, FileAPIReader(file)

  loadFromLink: ->
    url = @model.get("asset").asset.url
    @loadUrl url

  loadUrl: (url, reader) ->
    ID3.loadTags url, (->
      tags = ID3.getAllTags(url)
      $("#album").val(tags.album or "")
      if "picture" of tags
        image = tags.picture
        base64String = ""
        i = 0
        console.log(image.data.length)
        while i < image.data.length
          base64String += String.fromCharCode(image.data[i])
          i++
        $("#thumbnail").prop("src", "data:" + image.format + ";base64," + window.btoa(base64String))
        $("#thumbnail")[0].style.display = "block"
      else
        $("#thumbnail")[0].style.display = "none"
    ),
    tags: [
      "album"
      "picture"
    ],
    dataReader: reader
```
There are almost the same functions like in index.js from previously mentioned example (view-source:http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/index.js). The difference is my loadFromLink() is fired on render instead on link click.

**Problem is**:
the loadFromFile() works perfectly, but loadFromLink() shows only broken image icon. Asset url is ok, because album tag shows up correctly, only image doesn't load.

I noticed the content of base64String of mp3 from file is different than of this one from link (even if I choose the same uploaded file to which the link leads) but I have no idea why.

**Comment by aadsm** [comment]
It feels like this is a bug in the code that reads files loaded under XHR. This is most likely why it works with the FileAPI, they use different readers.
Is this only happening for one particular music file?

**Comment by RutSzymon** [comment]
I think you're right, because each music file gives you a different effect, such displays to half and the rest is gray or displays various artefacts.

**Comment by aadsm** [comment]
Can you share a music file where the issue happens?

**Comment by RutSzymon** [comment]
For example this: http://www52.zippyshare.com/v/XXmPRX8t/file.html
but for now it happened to any file I tried :)

**Comment by aadsm** [comment]
I have no problems reading the image in that file. Are you using the latest version?
If you're using the version I have on that website I don't think it's the latest one actually. Make sure you use this version: https://github.com/aadsm/JavaScript-ID3-Reader/blob/master/dist/id3-minimized.js

**Comment by RutSzymon** [comment]
Interesting... yes, I'm using the latest version from master. I also tried not minimized version.
Can I see your implementation (if it's different than on the website)? Maybe I do something wrong.

PS. I noticed I don't see any extra ajax request on server logs. Should I?

**Comment by aadsm** [comment]
Odd, I literally used a copy of what's on that page except I'm using an updated version of the library itself.
What do you mean with extra ajax requests?

**Comment by RutSzymon** [comment]
I was thinking, when I pass to ID3.loadTags function only url, cb and tags without reader it will send GET request to this url.

I copied source of http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/ with index.js and id3-minimized.js. Then I just swapped href of first link to "/uploads/song/asset/30/Let_Her_Go_-_Passenger__Grand_Piano_Cover_.mp3" and effect is exactly the same like in my app.
screen:
![zrzut ekranu z 2015-11-24 21 49 29](https://cloud.githubusercontent.com/assets/1850046/11380468/78eace26-92f6-11e5-81e0-1237ecddadeb.png)

**Comment by aadsm** [comment]
Exactly what I did, which browser are you using btw?

**Comment by RutSzymon** [comment]
Google Chrome 46.0.2490.86 (64-bit) and Firefox 42.0.

Your web page works perfectly, so maybe problem is in my Rails server? Can I somehow verify that file isn't served as compressed or is correctly fetched by BufferedBinaryAjax()?

**Comment by aadsm** [comment]
It could be an issue in the server side yeah... I don't think it's being served as compressed though, otherwise I wouldn't expect to see any part of the image.
The library uses Range requests, so it could be that there's an issue with the way those Range requests are being served?

**Comment by RutSzymon** [comment]
Unfortunately I don't know what exactly is the problem, but I think You're right, because probably Rails server doesn't handle http-range requests.
I tried this solution: http://stackoverflow.com/a/16593030, but it didn't work for me.. until I fetched the cover art on the server side and attached it to the json for testing:

**songs_controller.rb**
```ruby
def show
  if(request.headers["HTTP_RANGE"]) && Rails.env.development?
    file_path = "public" + song.asset.url
    size = File.size(file_path)
    bytes = Rack::Utils.byte_ranges(request.headers, size)[0]
    offset = bytes.begin
    length = bytes.end - bytes.begin + 1
    response.header["Accept-Ranges"]=  "bytes"
    response.header["Content-Range"] = "bytes #{bytes.begin}-#{bytes.end}/#{size}"
    response.header["Content-Length"] = "#{length}"

    send_data IO.binread(file_path,length, offset), type: "audio/mp3", stream: true,
      disposition: "inline", file_name: song.asset.url.split("/").last
  else
    TagLib::MPEG::File.open("public" + song.asset.url) do |mp3_file|
      tag = mp3_file.id3v2_tag
      cover = tag.frame_list('APIC').first
      @picture = cover.picture
    end
    respond_with song
  end
end
```
**songs/show.rabl.json**
```rabl
object @song
extends "songs/base"
node(:picture){ Base64.encode64(@picture) }
```
It isn't very elegant and I'm not sure why it's working (or why it isn't working without @picture in json), but I noticed that in this case the cover art is fetched from cache, so maybe that's why.

Anyway, I'm done with the simplest solution ever, I think. I just prepare the cover art on the server side:
```ruby
def cover_art
  TagLib::MPEG::File.open("public" + song.asset.url) do |mp3_file|
    tag = mp3_file.id3v2_tag
    cover = tag.frame_list("APIC").first
    @picture = cover.picture
  end
  send_data @picture, type: "image/jpg", stream: true, disposition: "inline"
end
```
and set src prop in image tag to this action on render.

Thank You very much for Your help and sorry for wasted time and my English :)

**Comment by aadsm** [comment]
No worries, I'm happy I could help in some way.
