### ISSUE TITLE
hey,  cant't it support IE & Chrome?

### ISSUE THREAD

**Issue by light0x00** [aadsm/JavaScript-ID3-Reader#63]
maybe ,i use it wrong ...hahaha.

**Comment by light0x00** [comment]
it's chrome error info ,but fire fox no problem.
i don't know how to deal with it..

Failed to load file:///C:/Users/Light/Desktop/%E5%89%8D%E7%AB%AF/%E6%92%AD%E6%94%BE%E5%99%A8ui/test2.mp3: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by aadsm** [comment]
You can’t access local files on the browser. You need to use http:// . That’s basically the problem. 
Also, I don’t support this library anymore, I created a new, better with many bug fixes, version: https://github.com/aadsm/jsmediatags.
